// Transaction Codes (tcode)
const TCODE_WRITE_QUAD_REQUEST    = 0
const TCODE_WRITE_BLOCK_REQUEST   = 1
const TCODE_WRITE_RESPONSE        = 2
const TCODE_READ_QUAD_REQUEST     = 4
const TCODE_READ_BLOCK_REQUEST    = 5
const TCODE_READ_QUAD_RESPONSE    = 6
const TCODE_READ_BLOCK_RESPONSE   = 7
// Opto 22 mem-map package sizes
const SIZE_WRITE_QUAD_REQUEST     = 16
const SIZE_WRITE_BLOCK_REQUEST    = 16
const SIZE_WRITE_RESPONSE         = 12
const SIZE_READ_QUAD_REQUEST      = 12
const SIZE_READ_BLOCK_REQUEST     = 16
const SIZE_READ_QUAD_RESPONSE     = 16
const SIZE_READ_BLOCK_RESPONSE    = 16

// Digital IO area
const BASE_DPOINT_WRITE           = 0xF0220000
const BASE_DPOINT_READ            = 0xF01E0000
const OFFSET_DPOINT_MOD           = 0x00001000
const OFFSET_DPOINT               = 0x00000040
// Analog IO area
const BASE_APOINT_WRITE           = 0xF02A0000
const BASE_APOINT_READ            = 0xF0260000
const OFFSET_APOINT_MOD           = 0x00001000
const OFFSET_APOINT               = 0x00000040
const OFFSET_APOINT_MIN           = 0x00000008
const OFFSET_APOINT_MAX           = 0x0000000C
// System status area
const BASE_IP_ADDRESS_ETH0        = 0xF0300034
const BASE_MAC_ADDRESS_ETH0       = 0xF030002E
const BASE_IP_ADDRESS_ETH1        = 0xFFFFF050
const BASE_MAC_ADDRESS_ETH1       = 0xFFFFF060
const BASE_FIRMWARE_VERSION       = 0xF030001C
const BASE_UNIT_DESCRIPTION       = 0xF0300080
const BASE_LAST_ERROR             = 0xF030000C
// ScratchPad area
//   string
const BASE_SCRATCHPAD_STRING      = 0xF0D83000
const OFFSET_SCRATCHPAD_STRING    = 0x00000082
const MAX_BYTES_STRING            = 0x00000410
//   float
const BASE_SCRATCHPAD_FLOAT       = 0xF0D82000
const BASE_SCRATCHPAD_FLOAT_1     = 0xF0D82000
const BASE_SCRATCHPAD_FLOAT_2     = 0xF0DC0000
const BASE_SCRATCHPAD_FLOAT_3     = 0xF0DC2000
const MAX_ELEMENTS_FLOAT_1        = 0x00000400
const MAX_ELEMENTS_FLOAT_2        = 0x00000800
const MAX_ELEMENTS_FLOAT_3        = 0x00001C00
const MAX_ELEMENTS_FLOAT          = MAX_ELEMENTS_FLOAT_1 + MAX_ELEMENTS_FLOAT_2 + MAX_ELEMENTS_FLOAT_3
const MAX_BYTES_FLOAT             = MAX_ELEMENTS_FLOAT * 4
//   integer
const BASE_SCRATCHPAD_INTEGER     = 0xF0D81000
const BASE_SCRATCHPAD_INTEGER_1   = 0xF0D81000
const BASE_SCRATCHPAD_INTEGER_2   = 0xF0DA0000
const BASE_SCRATCHPAD_INTEGER_3   = 0xF0DA2000
// integer
const MAX_ELEMENTS_INTEGER_1      = 0x00000400
const MAX_ELEMENTS_INTEGER_2      = 0x00000800
const MAX_ELEMENTS_INTEGER_3      = 0x00001C00
const MAX_ELEMENTS_INTEGER        = MAX_ELEMENTS_INTEGER_1 + MAX_ELEMENTS_INTEGER_2 + MAX_ELEMENTS_INTEGER_3
const MAX_BYTES_INTEGER           = MAX_ELEMENTS_INTEGER * 4

module.exports = {
  TCODE_WRITE_QUAD_REQUEST,
  TCODE_WRITE_BLOCK_REQUEST,
  TCODE_WRITE_RESPONSE,
  TCODE_READ_QUAD_REQUEST,
  TCODE_READ_BLOCK_REQUEST,
  TCODE_READ_QUAD_RESPONSE,
  TCODE_READ_BLOCK_RESPONSE,
  SIZE_WRITE_QUAD_REQUEST,
  SIZE_WRITE_BLOCK_REQUEST,
  SIZE_WRITE_RESPONSE,
  SIZE_READ_QUAD_REQUEST,
  SIZE_READ_BLOCK_REQUEST,
  SIZE_READ_QUAD_RESPONSE,
  SIZE_READ_BLOCK_RESPONSE,
  BASE_DPOINT_WRITE,
  BASE_DPOINT_READ,
  OFFSET_DPOINT_MOD,
  OFFSET_DPOINT,
  BASE_APOINT_WRITE,
  BASE_APOINT_READ,
  OFFSET_APOINT_MOD,
  OFFSET_APOINT,
  OFFSET_APOINT_MIN,
  OFFSET_APOINT_MAX,
  BASE_IP_ADDRESS_ETH0,
  BASE_MAC_ADDRESS_ETH0,
  BASE_IP_ADDRESS_ETH1,
  BASE_MAC_ADDRESS_ETH1,
  BASE_FIRMWARE_VERSION,
  BASE_UNIT_DESCRIPTION,
  BASE_LAST_ERROR,
  BASE_SCRATCHPAD_STRING,
  OFFSET_SCRATCHPAD_STRING,
  MAX_BYTES_STRING,
  BASE_SCRATCHPAD_FLOAT,
  BASE_SCRATCHPAD_FLOAT_1,
  BASE_SCRATCHPAD_FLOAT_2,
  BASE_SCRATCHPAD_FLOAT_3,
  MAX_ELEMENTS_FLOAT_1,
  MAX_ELEMENTS_FLOAT_2,
  MAX_ELEMENTS_FLOAT_3,
  MAX_ELEMENTS_FLOAT,
  MAX_BYTES_FLOAT,
  BASE_SCRATCHPAD_INTEGER,
  BASE_SCRATCHPAD_INTEGER_1,
  BASE_SCRATCHPAD_INTEGER_2,
  BASE_SCRATCHPAD_INTEGER_3,
  MAX_ELEMENTS_INTEGER_1,
  MAX_ELEMENTS_INTEGER_2,
  MAX_ELEMENTS_INTEGER_3,
  MAX_ELEMENTS_INTEGER,
  MAX_BYTES_INTEGER,
}